
window:
  position:
  #x: 0
  #y: 0

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
   x: 5
   y: 1

  decorations: none
  startup_mode: Windowed
  dynamic_title: true

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Scrolling distance multiplier.
  multiplier: 1

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: JetBrains Mono
    style: Regular

  # Bold font face
  bold:
    family: JetBrains Mono
    style: Bold

  # Italic font face
  italic:
    family: JetBrains Mono
    style: Italic

  # Bold italic font face
  bold_italic:
    family: JetBrains Mono
    style: Bold Italic

  # Point size
  size: 17.0

# Colors (Nord)
colors:
  primary:
    background: '#2e3440'
    foreground: '#d8dee9'
    dim_foreground: '#a5abb6'
  cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  vi_mode_cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  selection:
    text: CellForeground
    background: '#4c566a'
  search:
    matches:
      foreground: CellBackground
      background: '#88c0d0'
    bar:
      background: '#434c5e'
      foreground: '#d8dee9'
  normal:
    black: '#3b4252'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#88c0d0'
    white: '#e5e9f0'
  bright:
    black: '#4c566a'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#8fbcbb'
    white: '#eceff4'
  dim:
    black: '#373e4d'
    red: '#94545d'
    green: '#809575'
    yellow: '#b29e75'
    blue: '#68809a'
    magenta: '#8c738c'
    cyan: '#6d96a5'
    white: '#aeb3bb'


# Live config reload (changes require restart)
live_config_reload: true

# Shell
shell:
  program: /opt/homebrew/bin/tmux


mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true
    
key_bindings:

    # Select window 1-9
  - { key: Key1, mods: Command, chars: "\x02\x31" }
  - { key: Key2, mods: Command, chars: "\x02\x32" }
  - { key: Key3, mods: Command, chars: "\x02\x33" }
  - { key: Key4, mods: Command, chars: "\x02\x34" }
  - { key: Key5, mods: Command, chars: "\x02\x35" }
  - { key: Key6, mods: Command, chars: "\x02\x36" }
  - { key: Key7, mods: Command, chars: "\x02\x37" }
  - { key: Key8, mods: Command, chars: "\x02\x38" }
  - { key: Key9, mods: Command, chars: "\x02\x39" }

    # Create a new tmux window
  - { key: T, mods: Command, chars: "\x02\x63" }

    # Kill the current tmux pane (and window if last pane)
  - { key: W, mods: Command, chars: "\x02\x78" }

    # Change to the previous tmux window
  - { key: LBracket, mods: Command|Shift, chars: "\x02\x70" }

  # # Change to the next tmux window
  - { key: RBracket, mods: Command|Shift, chars: "\x02\x6e" }
  
     # Rename the current tmux window
  - { key: Comma, mods: Command, chars: "\x02\x2c" }

    # Split the current pane into two, left and right
  - { key: S, mods: Command|Shift, chars: "\x02\x25" }

    # Cooy and paste
  - { key: V,              mods: Command,                    action: Paste                 }
  - { key: C,              mods: Command,                    action: Copy                  }
